### ISSUE TITLE
Book 45 together ?

### ISSUE THREAD

**Issue by jexp** [mathbeveridge/asoiaf#2]
The books 4 and 5 are together in a single file. Is there a reason for that (except for being a split book with 2k pages)?

And the book column just contains "4"?

**Comment by mathbeveridge** [comment]
You are right-- I created one network, treating it as a 2K page book.

The network for asoiaf-book45-edges makes much more sense than the networks for the books when they are apart. I've added files for the individual books 4 and 5. You'll see what I mean when you bring up the networks. Very wacky.  

I've also updated the book column from 4 to 45. I kept it as an integer to be compatible with the other book files.
