### ISSUE TITLE
Calculate weight

### ISSUE THREAD

**Issue by brunopenso** [mathbeveridge/asoiaf#6]
Hi @mathbeveridge thanks for the contribution and I'm learning a lot using the https://github.com/neo4j-contrib/neovis.js/

I trying to use this to my use case here and I'm struggle on how to calculate weight between the nodes.

How did you do it?

Thanks

**Comment by mathbeveridge** [comment]
Hi Bruno,

I'm not an expert on neo4j but I'm very happy they use my data in their examples.  

Their [https://github.com/neo4j-contrib/neovis.js/#readme](https://github.com/neo4j-contrib/neovis.js/#readme) might have your answer? It looks like they LOAD CSV WITH HEADERS and then call toInteger(row.weight)

Good luck!
